import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';

export type TaskStatus = 'todo' | 'inprogress' | 'ready';

export interface FileItem {
  id: string;
  name: string;
  size: string;
  type: string;
}

export interface ProjectState {
  status: Record<string, TaskStatus>;
  files: Record<string, FileItem[]>;
  textData: Record<string, string>;
  talentCount?: number;
}

export interface Category {
  id: string;
  title: string;
  icon: string;
  desc: string;
}

export const CATEGORIES: Category[] = [
  { id: 'client-playbook', title: 'Client Playbook', icon: 'BookOpen', desc: 'Editable step-by-step client profile & SOP attachment' },
  { id: 'tech-setup', title: 'Tech Call Prep', icon: 'ShieldAlert', desc: 'Subdomain DNS, dedicated email, and calendar integrations' },
  { id: 'review-ai', title: 'Review AI Blueprint', icon: 'Star', desc: 'Configure Star Filters, Agent Prompts, & response footers' },
  { id: 'conversation-ai', title: 'Conversation AI Training', icon: 'MessageSquareText', desc: 'Configure crawler URLs, custom Q&A FAQs, and delay offsets' },
  { id: 'training-prep', title: 'Training Call Syllabus', icon: 'GraduationCap', desc: 'Contacts CRM, opportunities tracking, social planner, invoicing' },
  { id: 'launch-test', title: 'Launch Call Verification', icon: 'Activity', desc: '3-step test: Q&A call, routing check, and booking verification' },
  { id: 'assets-handover', title: 'Handover Bundle & Sign-off', icon: 'DownloadCloud', desc: 'Collect brand files, verify custom values, and finalize handover package' }
];

export const DEFAULT_CLIENT_PLAYBOOK = `# Client Blueprint & Onboarding Playbook

## 1. Business Profile
- **Company Name:** [Enter Business Name]
- **Target URL:** [e.g. www.clientwebsite.com]
- **Niche Industry:** [e.g. Dental Practice / HVAC]
- **Primary Stakeholders:** [Name & Role]
- **Core Timezone:** [e.g. EST / PST]

## 2. Revenue Leak Analysis
- **Identify active leaks (Select all that apply):**
  - [ ] Missed inbound calls during business hours
  - [ ] Long response delays (> 5 mins) on web/Zillow/ad leads
  - [ ] safety-declined recommendations go unchased
  - [ ] Treatment recommendations (crowns/recare) unbooked post-visit
  - [ ] After-hours inquiries or booking drop-offs
- **Estimated Annual Leak Cost:** $___________ / year

## 3. NWS Automation Configurations
- **AI Chatbot Agent Name:** Aria
- **Aria's Tone & Style:** [e.g., Warm, professional, informative, consultative]
- **Target Snapshot to Deploy:** [Generic Baseline / Niche Override]
- **Selected Expansion Modules:**
  - [ ] Missed Call Text-Back Automation
  - [ ] Automated Review Loop triggers (Google Reviews)
  - [ ] Long-term lead nurture sequence (WhatsApp/Email)
  - [ ] DMS / Practice Management System sync
  - [ ] Out-of-hours triage and emergency paging routing

## 4. Handover & SLA checklist
- [ ] GHL Sub-account successfully provisioned & Location ID recorded
- [ ] GHL snapshot deployed
- [ ] Custom prompts generated by AI Onboarding tool and copied into GHL (Vibe Coder, Ask AI, Automation Builder)
- [ ] Custom domain mapping complete
- [ ] Live call/chat tests verified (triage, calendar scheduling)
- [ ] Training SOPs shared with client team`;

export const DEFAULT_PROJECT_STATE: ProjectState = {
  status: {
    'client-playbook': 'todo',
    'tech-setup': 'todo',
    'review-ai': 'todo',
    'conversation-ai': 'todo',
    'training-prep': 'todo',
    'launch-test': 'todo',
    'assets-handover': 'todo'
  },
  files: {
    'assets-handover': []
  },
  textData: {
    clientPlaybook: DEFAULT_CLIENT_PLAYBOOK,
    techSetupNotes: '',
    reviewInstructions: '',
    reviewFooter: '',
    conversationDelay: '10',
    conversationLimit: '10',
    conversationUrls: '',
    conversationFaqs: '',
    trainingCallNotes: '',
    launchTestNotes: '',
    handoverNotes: ''
  },
  talentCount: 0
};

export function useProjectState(projectId: string | undefined, email: string | undefined) {
  const [state, setState] = useState<ProjectState>(DEFAULT_PROJECT_STATE);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);

  useEffect(() => {
    if (!projectId) return;

    async function loadState() {
      setIsLoading(true);
      const localKey = `nws_project_${projectId}`;
      const localData = localStorage.getItem(localKey);

      let loadedState: Partial<ProjectState> | null = null;
      if (localData) {
        try {
          loadedState = JSON.parse(localData);
        } catch (e) {
          console.error("Failed to parse local project state", e);
        }
      } else {
        try {
          const { data, error } = await supabase
            .from('projects')
            .select('state')
            .eq('project_id', projectId)
            .single();
          if (!error && data?.state) {
            loadedState = data.state;
          }
        } catch (err) {
          console.error("Failed to load project state from Supabase", err);
        }
      }

      if (loadedState) {
        const mergedState = {
          status: { ...DEFAULT_PROJECT_STATE.status, ...loadedState.status },
          files: { ...DEFAULT_PROJECT_STATE.files, ...loadedState.files },
          textData: { ...DEFAULT_PROJECT_STATE.textData, ...loadedState.textData },
          talentCount: loadedState.talentCount ?? 0,
        };

        if (!mergedState.textData.clientPlaybook) {
          mergedState.textData.clientPlaybook = DEFAULT_CLIENT_PLAYBOOK;
        }

        setState(mergedState);
      }
      setIsLoading(false);
    }

    loadState();
  }, [projectId]);

  const saveState = useCallback(async (newState: ProjectState) => {
    if (!projectId || !email) return;

    setIsSaving(true);
    setSaveSuccess(false);

    setState(newState);

    const localKey = `nws_project_${projectId}`;
    localStorage.setItem(localKey, JSON.stringify(newState));

    try {
      await supabase.from('projects').upsert({
        project_id: projectId,
        email: email,
        state: newState,
        updated_at: new Date().toISOString()
      }, { onConflict: 'project_id' });

      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 3000);
    } catch (err) {
      console.error("Failed to save state to Supabase", err);
    } finally {
      setIsSaving(false);
    }
  }, [projectId, email]);

  const updateCategoryStatus = useCallback((categoryId: string, status: TaskStatus) => {
    saveState({
      ...state,
      status: { ...state.status, [categoryId]: status }
    });
  }, [state, saveState]);

  const updateTextData = useCallback((key: string, value: string) => {
    saveState({
      ...state,
      textData: { ...state.textData, [key]: value }
    });
  }, [state, saveState]);

  const addFiles = useCallback((categoryId: string, files: File[]) => {
    const maxFileSize = 25 * 1024 * 1024;
    const newFiles: FileItem[] = [];

    files.forEach(file => {
      if (file.size > maxFileSize) {
        alert(`File ${file.name} exceeds 25MB limit.`);
        return;
      }
      const fileId = Math.random().toString(36).substr(2, 9);
      const k = 1024, i = Math.floor(Math.log(file.size) / Math.log(k));
      const sizeStr = `${parseFloat((file.size / Math.pow(k, i)).toFixed(2))} ${['B', 'KB', 'MB', 'GB'][i]}`;
      
      newFiles.push({
        id: fileId,
        name: file.name,
        size: sizeStr,
        type: file.type || file.name.split('.').pop() || 'unknown'
      });
    });

    const currentFiles = state.files[categoryId] || [];
    saveState({
      ...state,
      files: { ...state.files, [categoryId]: [...currentFiles, ...newFiles] }
    });
  }, [state, saveState]);

  const removeFile = useCallback((categoryId: string, fileId: string) => {
    const currentFiles = state.files[categoryId] || [];
    saveState({
      ...state,
      files: { ...state.files, [categoryId]: currentFiles.filter(f => f.id !== fileId) }
    });
  }, [state, saveState]);

  return {
    state,
    isLoading,
    isSaving,
    saveSuccess,
    saveState,
    updateCategoryStatus,
    updateTextData,
    addFiles,
    removeFile
  };
}
