import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { BookOpen, GraduationCap, ChevronRight, FileText } from "lucide-react";

const ACADEMY_ASSETS = [
  {
    id: "objection-handling",
    title: "Objection Handling Matrix",
    category: "Sales Script",
    content: `# Objection Handling Matrix

## 1. "We already have an agency"
**Acknowledge:** "That's great! It means you understand the value of marketing."
**Pivot:** "Most of our successful clients had an agency too. The difference is we don't just run ads; we implement a full AI reception and missed-call text-back system to ensure you capture the leads your current agency is generating. Are you currently capturing 100% of after-hours calls?"

## 2. "It's too expensive"
**Acknowledge:** "I completely understand keeping an eye on overhead."
**Pivot:** "Let's look at the math. How much is one missed client worth to your business? If our AI receptionist captures just *one* missed call per month that turns into a booked job, the system pays for itself and then some."

## 3. "We don't need AI"
**Acknowledge:** "A lot of business owners feel that way until they see the data."
**Pivot:** "Did you know 60% of consumers will go to the next business on Google if you don't answer the phone? Our AI isn't about replacing the human touch; it's about making sure your customers get a response instantly, 24/7."
`
  },
  {
    id: "demo-script",
    title: "Live Demo Script",
    category: "SOP",
    content: `# Live Demo Script

## Phase 1: Discovery & Rapport (5 mins)
- Build rapport.
- Identify the main pain point (usually missed calls, unorganized CRM, or poor review count).
- "How do you currently handle calls when your front desk is busy or closed?"

## Phase 2: The Demonstration (10 mins)
- **Action:** Have the prospect call the demo number.
- Let them interact with Aria.
- Show them the conversation logging in the GHL dashboard in real-time.
- "Imagine a customer calling at 9 PM on a Sunday. They get this immediate response and book directly into your calendar."

## Phase 3: The Offer & Close (5 mins)
- Present the Smart Start Package.
- "We can have this system deployed for your business in the next 48 hours. Should we get the onboarding started?"
`
  },
  {
    id: "handover-sop",
    title: "Extendly Handover SOP",
    category: "SOP",
    content: `# Extendly Handover SOP

## 1. Pre-Handover Requirements
- Provision GHL sub-account via the New Client Provisioning tool.
- Apply the correct industry snapshot.
- Generate and apply custom Vibe Coder and Ask AI prompts.

## 2. The Handover Call
- Introduce the Extendly support team to the client.
- Walk through the core dashboard features.
- Test the web chat widget and missed-call text-back live on the call.

## 3. Post-Call Actions
- Export the intake checklist.
- Verify DNS records for custom domains.
- Ensure billing is active and the first month is paid.
`
  }
];

export default function PortalAcademy() {
  const [selectedAssetId, setSelectedAssetId] = useState<string | null>(null);

  const selectedAsset = ACADEMY_ASSETS.find(a => a.id === selectedAssetId);

  return (
    <div className="p-6 max-w-7xl mx-auto w-full h-full flex flex-col">
      <div className="mb-8">
        <h1 className="text-3xl font-extrabold text-white mb-2 tracking-tight flex items-center gap-3">
          <GraduationCap className="text-purple-400 w-8 h-8" />
          Sales <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">Academy</span>
        </h1>
        <p className="text-slate-400 leading-relaxed max-w-2xl">
          Access live demo scripts, objection handling matrices, and standard operating procedures (SOPs) generated by Ronald using RonSuite OS.
        </p>
      </div>

      <div className="flex flex-col lg:flex-row gap-8 flex-1 min-h-[600px]">
        {/* Academy List */}
        <div className="w-full lg:w-1/3 flex flex-col gap-3">
          {ACADEMY_ASSETS.map(asset => (
            <button
              key={asset.id}
              onClick={() => setSelectedAssetId(asset.id)}
              className={`w-full text-left p-4 rounded-xl border transition-all flex items-center justify-between group ${
                selectedAssetId === asset.id 
                  ? "bg-slate-800 border-purple-500/50 shadow-[0_0_15px_rgba(168,85,247,0.15)]" 
                  : "bg-slate-900 border-slate-800 hover:bg-slate-800/80 hover:border-slate-700"
              }`}
            >
              <div className="flex items-center gap-4">
                <div className={`w-10 h-10 rounded-lg flex items-center justify-center shrink-0 ${
                  selectedAssetId === asset.id ? "bg-purple-500/20 text-purple-400" : "bg-slate-800 text-slate-400 group-hover:text-slate-300"
                }`}>
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h3 className={`font-bold text-sm ${selectedAssetId === asset.id ? "text-white" : "text-slate-300 group-hover:text-white"}`}>
                    {asset.title}
                  </h3>
                  <span className="text-xs font-semibold text-slate-500 uppercase tracking-widest mt-1 block">
                    {asset.category}
                  </span>
                </div>
              </div>
              <ChevronRight className={`w-4 h-4 transition-transform ${selectedAssetId === asset.id ? "text-purple-400" : "text-slate-600 group-hover:text-slate-400"} ${selectedAssetId === asset.id ? "translate-x-1" : ""}`} />
            </button>
          ))}
        </div>

        {/* Academy Viewer */}
        <div className="w-full lg:w-2/3 bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden flex flex-col shadow-xl">
          {!selectedAsset ? (
            <div className="flex-1 flex flex-col items-center justify-center p-12 text-center text-slate-500">
              <BookOpen className="w-16 h-16 text-purple-500/20 mb-4" />
              <p className="font-bold text-white mb-2 text-lg">Academy Viewer</p>
              <p className="text-sm max-w-sm">Select a training asset from the left to view the sales script or SOP.</p>
            </div>
          ) : (
            <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
              <div className="prose prose-invert prose-purple max-w-none">
                <ReactMarkdown
                  components={{
                    h1: ({node, ...props}) => <h1 className="text-2xl font-black text-white mb-6 pb-4 border-b border-slate-800" {...props} />,
                    h2: ({node, ...props}) => <h2 className="text-xl font-bold text-purple-400 mt-8 mb-4" {...props} />,
                    p: ({node, ...props}) => <p className="text-slate-300 leading-relaxed mb-4 text-sm" {...props} />,
                    ul: ({node, ...props}) => <ul className="list-disc list-outside pl-5 mb-4 text-slate-300 text-sm space-y-2" {...props} />,
                    li: ({node, ...props}) => <li className="pl-1" {...props} />,
                    strong: ({node, ...props}) => <strong className="text-white font-bold" {...props} />,
                  }}
                >
                  {selectedAsset.content}
                </ReactMarkdown>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
